### ISSUE TITLE
Milestones overlap

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#24] opened 2016-03-23 13:52 UTC
pramanavarttikavrtti.tex l. 2914:

```
      \leavevmode\marginnote{\textenglish{038/s}}\leavevmode\marginnote{\textenglish{8b/MA}}
```

![selection_079](https://cloud.githubusercontent.com/assets/11517856/13987158/83f506ec-f106-11e5-8b96-23a5cb179fb3.png)

pdf p. 29

**Comment by paddymcall** [comment] 2016-03-23 14:05
Duplicate of SARIT-pdf-conversions/issues/25

**Closed as completed by paddymcall** 2016-03-23 14:05 UTC
